namespace Pawnshop.Core
{
    public enum EntityType
    {
        None = 0,
        Contract = 10,
        CashOrder = 20,
        Selling = 30,
        Client = 40,
        Notification = 50,
        InnerNotification = 60,
        OnlinePayment = 70,
        Remittance = 80,
        Currency = 90,
        MintosContract = 100,
        PayOperation = 110,
        CBBatch = 120,
        CBBatchContract = 121,
        Verification = 130,
        DomainValue = 140,
        ClientContact = 150,
        Group = 160,
        Application = 170,
        Position = 180,
        ReportData = 190,
        JavaInsuranceService = 200,
        VehicleLiquidity = 210,
        Online1C = 220,
        Collection = 230,
        SoftCollection = 231,
        HardCollection = 232,
        LegalCollection = 233,
        LegalHardCollection = 234,
        CloseCollection = 235,
        InsurancePolicy = 240,
        InsurancePremium = 241,
        ApplicationOnline = 250,
        KatoData = 260,
        BitrixUpload = 270,
        BitrixUploadPayment = 271,
        BitrixGeneratePaymentQueue = 272,
        BitrixUploadContact = 273,
        ContractActionAutoStorno = 280,
        ClientDefermentsForRecruit = 290,
        CardTopUp = 300
    }
}